#include "BoardInOutConfig.h"
#include "BoardInOut.h"

//主板输入初始化
//配置输入上拉还是下拉
const GPIOPuPd_TypeDef boardInInitPullConfigArray[BOARD_IN_COUNT] = {
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN1_PH10
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN2_PH9
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN3_PH8
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN4_PH7
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN5_PH6
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN6_PF11
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN7_PB1
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN8_PB0
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN9_PC5
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN10_PC4
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN11_PH3
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN12_PH2
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN13_PA1
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN14_PA0
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN15_PB9
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN16_PI4
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN17_PI5
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN18_PI6
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN19_PI7
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN20_PF10
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN21_PF9
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN22_PF8
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN23_PF6
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN24_PF7
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN25_PI11
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN26_PI10
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN27_PI9
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN28_PC13
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN29_PI8
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN30_PE2
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN31_PE3
    GPIO_PuPd_DOWN,//BOARD_IN_ARM_SEN32_PE4
};


//板上IO初始化的电平状态配置
const BitAction  boardOutInitLevelConfigArray[BOARD_OUT_COUNT] = {
    Bit_SET,//BOARD_OUT_ARM_OUT1_PG15
    Bit_SET,//BOARD_OUT_ARM_OUT2_PB3
    Bit_SET,//BOARD_OUT_ARM_OUT3_PB4
    Bit_SET,//BOARD_OUT_ARM_OUT4_PG14
    Bit_SET,//BOARD_OUT_ARM_OUT5_PG13
    Bit_SET,//BOARD_OUT_ARM_OUT6_PG11
    Bit_SET,//BOARD_OUT_ARM_OUT7_PI3
    Bit_SET,//BOARD_OUT_ARM_OUT8_PA15
    Bit_SET,//BOARD_OUT_ARM_OUT9_PD6
    Bit_SET,//BOARD_OUT_ARM_OUT10_PG10
    Bit_SET,//BOARD_OUT_ARM_OUT11_PG9
    Bit_SET,//BOARD_OUT_ARM_OUT12_PG8
    Bit_SET,//BOARD_OUT_ARM_OUT13_PD7
    Bit_SET,//BOARD_OUT_ARM_OUT14_PI1
    Bit_SET,//BOARD_OUT_ARM_OUT15_PI0
    Bit_SET,//BOARD_OUT_ARM_OUT16_PG6
    Bit_SET,//BOARD_OUT_ARM_OUT17_PG7
    Bit_SET,//BOARD_OUT_ARM_OUT18_PH12
    Bit_SET,//BOARD_OUT_ARM_OUT19_PI2
    Bit_SET,//BOARD_OUT_ARM_OUT20_PD3
};


//板上IO初始化的上下拉配置
const GPIOPuPd_TypeDef  boardOutInitPullConfigArray[BOARD_OUT_COUNT] = {
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT1_PG15
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT2_PB3
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT3_PB4
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT4_PG14
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT5_PG13
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT6_PG11
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT7_PI3
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT8_PA15
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT9_PD6
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT10_PG10
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT11_PG9
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT12_PG8
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT13_PD7
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT14_PI1
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT15_PI0
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT16_PG6
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT17_PG7
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT18_PH12
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT19_PI2
    GPIO_PuPd_UP,//BOARD_OUT_ARM_OUT20_PD3
};
