#ifndef __CAN2_SUB_NEEDLE_LIQUID_DETECT_COMMON_H_
#define __CAN2_SUB_NEEDLE_LIQUID_DETECT_COMMON_H_

#include "Can2ProcMain.h"

//探液指令集
typedef enum CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD
{
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_CHECK_EXIST           = 0X00000003,//检测探液板是否存在
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_READ_THRESHOLD_VALUE  = 0X00000004,//读取探液板检测阈值
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_READ_THRESHOLD_COUNT  = 0X00000005,//读取探液板检测阈值计数
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_READ_CLOPE_VALUE      = 0X00000006,//读取探液板检测斜率
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_READ_SLOPE_COUNT      = 0X00000007,//读取探液板检测斜率计数
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_READ_SIGNAL_HOLD      = 0X00000008,//读取探液板信号保持时间
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_READ_RES              = 0X00000009,//读取探液板基准电阻
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_WRITE_RES             = 0X0000000A,//写入探液板基准电阻
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_ADJUST                = 0X0000000B,//探液板自动校准
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_ENABLE_FUNC           = 0X0000000C,//探液板功能使能
    CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD_DISABLE_FUNC          = 0X0000000D,//探液功能关闭
}CAN2_SUB_NEEDLE_LIQUID_DETECT_CMD;

//不同的针的板号
//样本针所在板号
#define NEEDLE_SAMPLE_BOARD_ID          CAN2_SUB_BOARD4
//磁珠针所在板号
#define NEEDLE_BEAD_BOARD_ID            CAN2_SUB_BOARD3
//试剂针所在板号
#define NEEDLE_REAGENT_BOARD_ID         CAN2_SUB_BOARD2

#endif





