#ifndef __CAN2_SUB_STEP_MOTOR_INDEX_H_
#define __CAN2_SUB_STEP_MOTOR_INDEX_H_
#include "ErrorCode.h"

//系统下位机步进电机序号
typedef enum CAN2_SUB_SM_INDEX
{
    //Board1
    CAN2_SUB_SM_BOARD1_SM1,CAN2_SUB_SM_BOARD1_SM2,CAN2_SUB_SM_BOARD1_SM3,CAN2_SUB_SM_BOARD1_SM4,
    CAN2_SUB_SM_BOARD1_SM5,CAN2_SUB_SM_BOARD1_SM6,CAN2_SUB_SM_BOARD1_SM7,CAN2_SUB_SM_BOARD1_SM8,
    CAN2_SUB_SM_BOARD1_SM9,CAN2_SUB_SM_BOARD1_SM10,CAN2_SUB_SM_BOARD1_SM11,CAN2_SUB_SM_BOARD1_SM12,
    //Board2
    CAN2_SUB_SM_BOARD2_SM1,CAN2_SUB_SM_BOARD2_SM2,CAN2_SUB_SM_BOARD2_SM3,CAN2_SUB_SM_BOARD2_SM4,
    CAN2_SUB_SM_BOARD2_SM5,CAN2_SUB_SM_BOARD2_SM6,CAN2_SUB_SM_BOARD2_SM7,CAN2_SUB_SM_BOARD2_SM8,
    CAN2_SUB_SM_BOARD2_SM9,CAN2_SUB_SM_BOARD2_SM10,CAN2_SUB_SM_BOARD2_SM11,CAN2_SUB_SM_BOARD2_SM12,
    //Board3
    CAN2_SUB_SM_BOARD3_SM1,CAN2_SUB_SM_BOARD3_SM2,CAN2_SUB_SM_BOARD3_SM3,CAN2_SUB_SM_BOARD3_SM4,
    CAN2_SUB_SM_BOARD3_SM5,CAN2_SUB_SM_BOARD3_SM6,CAN2_SUB_SM_BOARD3_SM7,CAN2_SUB_SM_BOARD3_SM8,
    CAN2_SUB_SM_BOARD3_SM9,CAN2_SUB_SM_BOARD3_SM10,CAN2_SUB_SM_BOARD3_SM11,CAN2_SUB_SM_BOARD3_SM12,
    //Board4
    CAN2_SUB_SM_BOARD4_SM1,CAN2_SUB_SM_BOARD4_SM2,CAN2_SUB_SM_BOARD4_SM3,CAN2_SUB_SM_BOARD4_SM4,
    CAN2_SUB_SM_BOARD4_SM5,CAN2_SUB_SM_BOARD4_SM6,CAN2_SUB_SM_BOARD4_SM7,CAN2_SUB_SM_BOARD4_SM8,
    CAN2_SUB_SM_BOARD4_SM9,CAN2_SUB_SM_BOARD4_SM10,CAN2_SUB_SM_BOARD4_SM11,CAN2_SUB_SM_BOARD4_SM12,
    //Board5
    CAN2_SUB_SM_BOARD5_SM1,CAN2_SUB_SM_BOARD5_SM2,CAN2_SUB_SM_BOARD5_SM3,CAN2_SUB_SM_BOARD5_SM4,
    CAN2_SUB_SM_BOARD5_SM5,CAN2_SUB_SM_BOARD5_SM6,CAN2_SUB_SM_BOARD5_SM7,CAN2_SUB_SM_BOARD5_SM8,
    CAN2_SUB_SM_BOARD5_SM9,CAN2_SUB_SM_BOARD5_SM10,CAN2_SUB_SM_BOARD5_SM11,CAN2_SUB_SM_BOARD5_SM12,
    //Board6
    CAN2_SUB_SM_BOARD6_SM1,CAN2_SUB_SM_BOARD6_SM2,CAN2_SUB_SM_BOARD6_SM3,CAN2_SUB_SM_BOARD6_SM4,
    CAN2_SUB_SM_BOARD6_SM5,CAN2_SUB_SM_BOARD6_SM6,CAN2_SUB_SM_BOARD6_SM7,CAN2_SUB_SM_BOARD6_SM8,
    CAN2_SUB_SM_BOARD6_SM9,CAN2_SUB_SM_BOARD6_SM10,CAN2_SUB_SM_BOARD6_SM11,CAN2_SUB_SM_BOARD6_SM12,
    //Board7
    CAN2_SUB_SM_BOARD7_SM1,CAN2_SUB_SM_BOARD7_SM2,CAN2_SUB_SM_BOARD7_SM3,CAN2_SUB_SM_BOARD7_SM4,
    CAN2_SUB_SM_BOARD7_SM5,CAN2_SUB_SM_BOARD7_SM6,CAN2_SUB_SM_BOARD7_SM7,CAN2_SUB_SM_BOARD7_SM8,
    CAN2_SUB_SM_BOARD7_SM9,CAN2_SUB_SM_BOARD7_SM10,CAN2_SUB_SM_BOARD7_SM11,CAN2_SUB_SM_BOARD7_SM12,
    //Board8
    CAN2_SUB_SM_BOARD8_SM1,CAN2_SUB_SM_BOARD8_SM2,CAN2_SUB_SM_BOARD8_SM3,CAN2_SUB_SM_BOARD8_SM4,
    CAN2_SUB_SM_BOARD8_SM5,CAN2_SUB_SM_BOARD8_SM6,CAN2_SUB_SM_BOARD8_SM7,CAN2_SUB_SM_BOARD8_SM8,
    CAN2_SUB_SM_BOARD8_SM9,CAN2_SUB_SM_BOARD8_SM10,CAN2_SUB_SM_BOARD8_SM11,CAN2_SUB_SM_BOARD8_SM12,
    //Board9
    CAN2_SUB_SM_BOARD9_SM1,CAN2_SUB_SM_BOARD9_SM2,CAN2_SUB_SM_BOARD9_SM3,CAN2_SUB_SM_BOARD9_SM4,
    CAN2_SUB_SM_BOARD9_SM5,CAN2_SUB_SM_BOARD9_SM6,CAN2_SUB_SM_BOARD9_SM7,CAN2_SUB_SM_BOARD9_SM8,
    CAN2_SUB_SM_BOARD9_SM9,CAN2_SUB_SM_BOARD9_SM10,CAN2_SUB_SM_BOARD9_SM11,CAN2_SUB_SM_BOARD9_SM12,
    //Board10
    CAN2_SUB_SM_BOARD10_SM1,CAN2_SUB_SM_BOARD10_SM2,CAN2_SUB_SM_BOARD10_SM3,CAN2_SUB_SM_BOARD10_SM4,
    CAN2_SUB_SM_BOARD10_SM5,CAN2_SUB_SM_BOARD10_SM6,CAN2_SUB_SM_BOARD10_SM7,CAN2_SUB_SM_BOARD10_SM8,
    CAN2_SUB_SM_BOARD10_SM9,CAN2_SUB_SM_BOARD10_SM10,CAN2_SUB_SM_BOARD10_SM11,CAN2_SUB_SM_BOARD10_SM12,
}CAN2_SUB_SM_INDEX;


//系统内部电机编号

/*******************************************系统内部使用的电机宏定义***************************************************/

/*****************************************下位机板1的步进电机***************************************/
//清洗针注射泵1
#define STEP_MOTOR_PUMP_CLEAN1                  CAN2_SUB_SM_BOARD1_SM1
//清洗针注射泵2
#define STEP_MOTOR_PUMP_CLEAN2                  CAN2_SUB_SM_BOARD1_SM2
//清洗针注射泵3
#define STEP_MOTOR_PUMP_CLEAN3                  CAN2_SUB_SM_BOARD1_SM3
//清洗盘旋转
#define STEP_MOTOR_DISH_WASH_ROTATE             CAN2_SUB_SM_BOARD1_SM4
//注A液泵
#define STEP_MOTOR_PUMP_LIQUID_A                CAN2_SUB_SM_BOARD1_SM5
//清洗摇匀旋转
#define STEP_MOTOR_SHAKE_WASH_ROTATE            CAN2_SUB_SM_BOARD1_SM6
//清洗摇匀升降
#define STEP_MOTOR_SHAKE_WASH_UPDOWN            CAN2_SUB_SM_BOARD1_SM7
//清洗针升降
#define STEP_MOTOR_NEEDLE_WASH_UPDOWN           CAN2_SUB_SM_BOARD1_SM8
//废液泵
#define STEP_MOTOR_PUMP_WASTE                   CAN2_SUB_SM_BOARD1_SM9
/*******************************************************************************************************/

/*****************************************下位机板2的步进电机***************************************/
//试剂摇匀升降
#define STEP_MOTOR_SHAKE_REAGENT_UPDOWN         CAN2_SUB_SM_BOARD2_SM1
//磁珠摇匀升降
#define STEP_MOTOR_SHAKE_BEAD_UPDOWN            CAN2_SUB_SM_BOARD2_SM2
//试剂摇匀旋转
#define STEP_MOTOR_SHAKE_REAGENT_ROTATE         CAN2_SUB_SM_BOARD2_SM3
//磁珠摇匀旋转
#define STEP_MOTOR_SHAKE_BEAD_ROTATE            CAN2_SUB_SM_BOARD2_SM4
//试剂磁珠针升降
#define STEP_MOTOR_NEEDLE_REAGENT_BEAD_UPDOWN   CAN2_SUB_SM_BOARD2_SM5
//试剂磁珠针注射泵
#define STEP_MOTOR_PUMP_NEEDLE_REAGENT_BEAD     CAN2_SUB_SM_BOARD2_SM6
//试剂磁珠针旋转
#define STEP_MOTOR_NEEDLE_REAGENT_BEAD_ROTATE   CAN2_SUB_SM_BOARD2_SM7
//反应盘旋转
#define STEP_MOTOR_DISH_REACTION_ROTATE         CAN2_SUB_SM_BOARD2_SM8

/*******************************************************************************************************/

/*****************************************下位机板3的步进电机***************************************/
//抓杯机械手左右
#define STEP_MOTOR_HAND_CUP_LEFTRIGHT           CAN2_SUB_SM_BOARD3_SM1
//抓杯机械手前后
#define STEP_MOTOR_HAND_CUP_FRONTBACK           CAN2_SUB_SM_BOARD3_SM2
//新杯栈上升
#define STEP_MOTOR_NEW_CUP_STACK_UPDOWN         CAN2_SUB_SM_BOARD3_SM3
//新杯栈下降
#define STEP_MOTOR_EMPTY_CUP_STACK_UPDOWN       CAN2_SUB_SM_BOARD3_SM4
//杯栈夹紧
#define STEP_MOTOR_CUP_HOLDER                   CAN2_SUB_SM_BOARD3_SM5
//杯栈前推
#define STEP_MOTOR_CUP_PUSH                     CAN2_SUB_SM_BOARD3_SM6
//新杯机械手升降
#define STEP_MOTOR_HAND_CUP_UPDOWN              CAN2_SUB_SM_BOARD3_SM7

/*******************************************************************************************************/

/*****************************************下位机板4的步进电机***************************************/
//测量室上门
#define STEP_MOTOR_MEASUREROOM_WINDOW           CAN2_SUB_SM_BOARD4_SM1
//测量室侧门
#define STEP_MOTOR_MEASUREROOM_UP_DOOR          CAN2_SUB_SM_BOARD4_SM2
//注B液泵
#define STEP_MOTOR_PUMP_LIQUID_B                CAN2_SUB_SM_BOARD4_SM3
//试剂盘旋转
#define STEP_MOTOR_DISH_REAGENT_ROTATE          CAN2_SUB_SM_BOARD4_SM4
//试管架传送带
#define STEP_MOTOR_TEST_TUBE_RACK_CONVEYOR      CAN2_SUB_SM_BOARD4_SM5
//样本针注射泵
#define STEP_MOTOR_PUMP_NEEDLE_SAMPLE           CAN2_SUB_SM_BOARD4_SM6
//样本针升降
#define STEP_MOTOR_NEEDLE_SAMPLE_UPDOWN         CAN2_SUB_SM_BOARD4_SM7
//样本针旋转
#define STEP_MOTOR_NEEDLE_SAMPLE_ROTATE         CAN2_SUB_SM_BOARD4_SM8

/*******************************************************************************************************/

















#endif




