#ifndef __CAN2_SUB_SERIAL_INDEX_H_
#define __CAN2_SUB_SERIAL_INDEX_H_
#include "ErrorCode.h"

//下位机的子串口定义
typedef enum CAN2_SUB_SERIAL
{
    CAN2_SUB_BOARD1_SERIAL,
    CAN2_SUB_BOARD2_SERIAL,
    CAN2_SUB_BOARD3_SERIAL,
    CAN2_SUB_BOARD4_SERIAL,
    CAN2_SUB_BOARD5_SERIAL,
    CAN2_SUB_BOARD6_SERIAL,
    CAN2_SUB_BOARD7_SERIAL,
    CAN2_SUB_BOARD8_SERIAL,
    CAN2_SUB_BOARD9_SERIAL,
    CAN2_SUB_BOARD10_SERIAL,
}CAN2_SUB_SERIAL;

#endif




