#ifndef __SYSTEM_OUTPUT_H_
#define __SYSTEM_OUTPUT_H_
#include "SystemOutputIndex.h"
#include "BoardInc.h"
#include "Can2SubOutputWrite.h"

/*系统输出宏定义*/


//垃圾桶1正转 0有效 垃圾桶降下去
#define GARBAGE1_CLOCK_WISE             SYSTEM_OUTPUT_LOW_BOARD3_MCU_SLAVE_DC4_PI3   
//垃圾桶1反转 0有效 垃圾桶升起来 
#define GARBAGE1_ANTI_CLOCK_WISE        SYSTEM_OUTPUT_LOW_BOARD3_MCU_SLAVE_DC5_PI2

//垃圾桶2正转 0有效 垃圾桶升起来
#define GARBAGE2_CLOCK_WISE             SYSTEM_OUTPUT_LOW_BOARD3_MCU_SLAVE_DC2_PG9
//垃圾桶2反转 0有效 垃圾桶降下去
#define GARBAGE2_ANTI_CLOCK_WISE        SYSTEM_OUTPUT_LOW_BOARD3_MCU_SLAVE_DC3_PD6

//反应盘电磁铁
#define DISH_REACTION_ELECTRO_MAGNET    SYSTEM_OUTPUT_LOW_BOARD3_MCU_SLAVE_DC1_PC8

//清洗盘电磁铁
#define DISH_WASH_ELECTRO_MAGNET        SYSTEM_OUTPUT_LOW_BOARD1_MCU_SLAVE_DC1_PC8

//清洗针1进液三通阀                       
#define NEEDLEWASH_TEE_1                SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC17

//清洗针2进液三通阀                       
#define NEEDLEWASH_TEE_2                SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC18

//清洗针3进液三通阀                       
#define NEEDLEWASH_TEE_3                SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC19

//排液二通阀V306
//#define DRAINAGE_VALVE_V306             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC14

//废液泵DP2
#define WASTE_LIQUID_PUMP2              SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC23

//废液泵DP1
#define WASTE_LIQUID_PUMP               SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC29

//排液二通阀v307
#define DRAINAGE_VALVE_V307             SYSTEM_OUTPUT_LOW_BOARD1_MCU_SLAVE_SEN19_PA6

//进液二通阀v221
#define DRAINAGE_VALVE_V221             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC16

//清洗二通阀v218
#define DRAINAGE_VALVE_V218             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC30

//隔膜泵dp307
#define DIAPHRAGM_PUMP_DP307            SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC34

//隔膜泵dp305
#define DIAPHRAGM_PUMP_DP305            SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC36

//阀v215
#define DRAINAGE_VALVE_V215             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC33

//隔膜泵dp304
#define DIAPHRAGM_PUMP_DP304            SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC27

//阀v219
#define DRAINAGE_VALVE_V219             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC14

//阀v216
#define DRAINAGE_VALVE_V216             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC32
//泵dp306
#define DIAPHRAGM_PUMP_DP306            SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC35

//阀v201
#define DRAINAGE_VALVE_V201             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC13

//阀v202
#define DRAINAGE_VALVE_V202             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC12

//阀v203
#define DRAINAGE_VALVE_V203             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC11

//阀v204
#define DRAINAGE_VALVE_V204             SYSTEM_OUTPUT_LOW_BOARD1_CPLD_CDC10

//系统端口写入
LH_ERR SystemOutputWrite(SYSTEM_OUTPUT_INDEX outIndex,BitAction setValue);

#endif





