#ifndef __TESTPROC_WARNING_H_
#define __TESTPROC_WARNING_H_
#include "TSC_Inc.h"
#include "TestProc_Typedef.h"

// Warning Level
#define WARNING_LEVEL_EMSTOP                        (1)     // 急停级报警
#define WARNING_LEVEL_STOP                          (2)     // 停止级报警
#define WARNING_LEVEL_NOTICE                        (3)     // 注意级报警
#define WARNING_LEVEL_DEBUG                         (4)     // 调试级报警

#pragma pack (1)    // 指定按1字节对齐
typedef struct 
{
    uint8_t  u8Board;
    uint8_t  u8Level;
    uint8_t  u8Code;     // 小类
    uint8_t  u8Type;     // 大类
}TESTPROC_WARNING_T;
#pragma pack ()     // 取消指定对齐，恢复缺省对齐

typedef enum
{
    TESTPROC_WARNING_COMMUNICATE = 0,
    // Reset
    TESTPROC_WARNING_RESET_TIMEOUT_REACT,
    TESTPROC_WARNING_RESET_TIMEOUT_WASH,
    TESTPROC_WARNING_RESET_TIMEOUT_REAGENTDISK,
    TESTPROC_WARNING_RESET_TIMEOUT_REAGENT,
    TESTPROC_WARNING_RESET_TIMEOUT_SAMPLE,
    TESTPROC_WARNING_RESET_TIMEOUT_HANDCUP,
    TESTPROC_WARNING_RESET_TIMEOUT_CUPSTACK,
    TESTPROC_WARNING_RESET_NG_REACT,
    TESTPROC_WARNING_RESET_NG_WASH,
    TESTPROC_WARNING_RESET_NG_REAGENTDISK,
    TESTPROC_WARNING_RESET_NG_REAGENT,
    TESTPROC_WARNING_RESET_NG_SAMPLE,
    TESTPROC_WARNING_RESET_NG_HANDCUP,
    TESTPROC_WARNING_RESET_NG_CUPSTACK,
    // Command
    TESTPROC_WARNING_CMD_RSP_GETITEM,
    // React
    TESTPROC_WARNING_REACT_IF_HANDCUP,          
    TESTPROC_WARNING_REACT_IF_REAGENT,
    TESTPROC_WARNING_REACT_IF_SAMPLE,
    TESTPROC_WARNING_REACT_IF_MIX1,
    TESTPROC_WARNING_REACT_IF_MIX2,
    TESTPROC_WARNING_REACT_RUN_TRIGGER_23,
    TESTPROC_WARNING_REACT_RUN_TRIGGER_2,
    TESTPROC_WARNING_REACT_RUN_TRIGGER_9,
    TESTPROC_WARNING_REACT_RUN_TRIGGER_31,    
    TESTPROC_WARNING_REACT_STOP_TRIGGER_23,
    TESTPROC_WARNING_REACT_STOP_TRIGGER_2,
    TESTPROC_WARNING_REACT_STOP_TRIGGER_9,
    TESTPROC_WARNING_REACT_STOP_TRIGGER_31,
    TESTPROC_WARNING_REACT_RUN_TYPE,
    TESTPROC_WARNING_REACT_STOP_TYPE,
    TESTPROC_WARNING_REACT_IF_REAGENT2,
    // Wash
    TESTPROC_WARNING_WASHDISK_IF_NEEDLE,
    TESTPROC_WARNING_WASHDISK_IF_HANDCUP,
    // HandCup
    TESTPROC_WARNING_HANDCUP_INREACT_1,
    TESTPROC_WARNING_HANDCUP_INREACT_2,
    // Reagent
    TESTPROC_WARNING_REAGENT_1_INJECT,
    TESTPROC_WARNING_REAGENT_2_INJECT,
    TESTPROC_WARNING_REAGENT_POSTION,
    // Cup Stack
    TESTPROC_WARNING_CUPSTACK_STATUS,
    TESTPROC_WARNING_CUPSTACK_EMPTY,
    // Flow
    TESTPROC_WARNING_FLOW_EMRACK_IN,
    TESTPROC_WARNING_FLOW_RACK_IN,
    TESTPROC_WARNING_FLOW_ITEM_LOST,
    TESTPROC_WARNING_FLOW_WASH_INCUP_STATE,
    TESTPROC_WARNING_FLOW_ITEM_LOST_RD,
    //Time Out
    TESTPROC_WARNING_TIMEOUT_REACT_STEP1,
    TESTPROC_WARNING_TIMEOUT_REACT_STEP2,
    TESTPROC_WARNING_TIMEOUT_REACT_STEP3,
    TESTPROC_WARNING_TIMEOUT_REACT_STEP4,
    TESTPROC_WARNING_TIMEOUT_REACT_MIX,
    TESTPROC_WARNING_TIMEOUT_HANDCUP_CATCH_NEWCUP, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_TO_REACT, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_PUT_REACT, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_REACT_TO_WASH, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_PUT_WASH, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_TO_MR, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_PUT_MR, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_MR_ABANDON, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_WASH_TO_REACT, 
    TESTPROC_WARNING_TIMEOUT_HANDCUP_WASH_PUT_REAC, 
    TESTPROC_WARNING_TIMEOUT_SAMPLE_TO_REACT, 
    TESTPROC_WARNING_TIMEOUT_SAMPLE_ABSORB, 
    TESTPROC_WARNING_TIMEOUT_SAMPLE_INJECT, 
    TESTPROC_WARNING_TIMEOUT_SAMPLE_FORCE_CLEAN, 
    TESTPROC_WARNING_TIMEOUT_SAMPLE_CLEAN, 
    TESTPROC_WARNING_TIMEOUT_RS1_R1_PREPARE, 
    TESTPROC_WARNING_TIMEOUT_RS1_R1, 
    TESTPROC_WARNING_TIMEOUT_RS1_R2, 
    TESTPROC_WARNING_TIMEOUT_RS1_STEP2_R2_PREPARE, 
    TESTPROC_WARNING_TIMEOUT_RS1_STEP2_R2, 
    TESTPROC_WARNING_TIMEOUT_RS1_R1_INJECT, 
    TESTPROC_WARNING_TIMEOUT_RS2_R2_PREPARE, 
    TESTPROC_WARNING_TIMEOUT_RS2_R2, 
    TESTPROC_WARNING_TIMEOUT_RS2_R3_CLEAN, 
    TESTPROC_WARNING_TIMEOUT_RS2_R3_PREPARE, 
    TESTPROC_WARNING_TIMEOUT_RS2_R3, 
    TESTPROC_WARNING_TIMEOUT_RS2_M_CLEAN, 
    TESTPROC_WARNING_TIMEOUT_RS2_M_PREPARE, 
    TESTPROC_WARNING_TIMEOUT_RS2_M, 
    TESTPROC_WARNING_TIMEOUT_RS2_INJECT, 
    TESTPROC_WARNING_TIMEOUT_REAGENTDISK_MOVE, 
    TESTPROC_WARNING_TIMEOUT_WASH_ROTATE, 
    TESTPROC_WARNING_TIMEOUT_WASH_CLEAN, 
    TESTPROC_WARNING_TIMEOUT_MR_FULLOPEN, 
    TESTPROC_WARNING_TIMEOUT_MR_HALFOPEN, 
    TESTPROC_WARNING_TIMEOUT_MR_CLOSE, 
    TESTPROC_WARNING_TIMEOUT_CB_MOVE_POSITION, 
    TESTPROC_WARNING_TIMEOUT_CB_RECYCLE, 
    TESTPROC_WARNING_TIMEOUT_CUPSTACK_PUSH, 
    TESTPROC_WARNING_TIMEOUT_CUPSTACK_CHANGE, 
    TESTPROC_WARNING_TIMEOUT_REAGENT_TO_REACT,
    // Api Exec NG
    TESTPROC_WARNING_API_NG_REAGENT_ROTATE,
    TESTPROC_WARNING_API_NG_ABSORB_RS1_R1_ING,
    TESTPROC_WARNING_API_NG_ABSORB_RS1_STEP2_R2,
    TESTPROC_WARNING_API_NG_CLEAN_OUT,
    TESTPROC_WARNING_API_NG_ABSORB_RS1_R2_ING,
    TESTPROC_WARNING_API_NG_INJECT_RS1,
    TESTPROC_WARNING_API_NG_CLEAN_INOUT,
    TESTPROC_WARNING_API_NG_ABSORB_RS2_R2_ING,
    TESTPROC_WARNING_API_NG_ABSORB_RS2_R3_ING,
    TESTPROC_WARNING_API_NG_ABSORB_RS2_M_ING,
    TESTPROC_WARNING_API_NG_INJECT_RS2,
    TESTPROC_WARNING_API_NG_REAGENTDISK_MOVE,
    TESTPROC_WARNING_API_NG_CONVEYORBELT_MOVE,
    TESTPROC_WARNING_API_NG_SAMPLE_ROTATE,
    TESTPROC_WARNING_API_NG_ABSORB_SAMPLE,
    TESTPROC_WARNING_API_NG_INJECT_SAMPLE,
    TESTPROC_WARNING_API_NG_SAMPLE_FORCE_CLEAN,
    TESTPROC_WARNING_API_NG_SAMPLE_CLEAN,
    TESTPROC_WARNING_API_NG_TO_CUPSTACK,
    TESTPROC_WARNING_API_NG_TO_REACT,
    TESTPROC_WARNING_API_NG_TO_WASHDISK,
    TESTPROC_WARNING_API_NG_TO_MR,
    TESTPROC_WARNING_API_NG_TO_GARBAGE,
    TESTPROC_WARNING_API_NG_HANDCUP_CATCH,
    TESTPROC_WARNING_API_NG_HANDCUP_PUT,
    TESTPROC_WARNING_API_NG_CUPSTACK_UPLOAD,
    TESTPROC_WARNING_API_NG_CUPSTACK_PUSH,
    TESTPROC_WARNING_API_NG_CUPSTACK_RECYCLE,
    TESTPROC_WARNING_API_NG_REACT_ROTATE,
    TESTPROC_WARNING_API_NG_REACT_MIX,
    TESTPROC_WARNING_API_NG_WASHDISK_ROTATE,
    TESTPROC_WARNING_API_NG_WASHNEEDLE_CLEAN1,
    TESTPROC_WARNING_API_NG_WASHNEEDLE_CLEAN2,
    TESTPROC_WARNING_API_NG_MR_FULLOPEN,
    TESTPROC_WARNING_API_NG_MR_HALFOPEN,
    TESTPROC_WARNING_API_NG_MR_CLOSE,
    TESTPROC_WARNING_API_NG_MR_BACK,
    TESTPROC_WARNING_API_NG_MR_VALUE,
    // Debug
    TESTPROC_WARNING_DEBUG1_SEND_MSG,
    TESTPROC_WARNING_DEBUG1_MSG,
    TESTPROC_WARNING_NONE,
    TESTPROC_WARNING_MAX,
    //TESTPROC_WARNING_ERROR = 0xFFFF
}TESTPROC_WARNING_E;

extern const TESTPROC_WARNING_T g_stWarningCode[TESTPROC_WARNING_MAX];

#endif // End of “ifndef __TESTPROC_WARNING_H_

