
#include "TestProc_Warning.h"
#include "TestProc_boardID.h"
//#include "TestProc_CanConfig.h"

// Warning Type
#define WARNING_TYPE_COMM                           (101)    // 通信类报警
#define WARNING_TYPE_RESET                          (103)    // 通信类报警
#define WARNING_TYPE_WORK_TYPE                      (104)    // 模块1启动失败
#define WARNING_TYPE_CMD                            (105)    // 未知命令
#define WARNING_TYPE_CAN1CMD                        (106)    // CAN1命令错误
#define WARNING_TYPE_MEM                            (107)    // 内存类错误
#define WARNING_TYPE_REACT                          (108)    // 反应盘机构报警
#define WARNING_TYPE_HANDCUP                        (109)    // 抓杯机械手机构报警
#define WARNING_TYPE_SAMPLE                         (110)    // 样本针机构报警
#define WARNING_TYPE_REAGENT                        (111)    // 试剂针机构报警
#define WARNING_TYPE_WASH                           (112)    // 清洗机构报警
#define WARNING_TYPE_CB                             (113)    // 传送带机构报警
#define WARNING_TYPE_CUPSTACK                       (114)    // 反应杯栈机构报警
#define WARNING_TYPE_MR                             (115)    // 测量室机构报警
#define WARNING_TYPE_FLOW                           (116)    // 测试流程报警
#define WARNING_TYPE_TIMEOUT                        (117)    // 机构超时报警
#define WARNING_TYPE_API_NG                         (118)    // 机构执行失败报警

#define WARNING_TYPE_DEBUG_1                        (252)   // 调试数据

// Warning Code
#define WARNING_CODE_COMMUNICATE                    (0)     // 通信故障

// Reset
#define WARNING_CODE_RESET_TIMEOUT_REACT            (0)     // 反应盘机构复位超时
#define WARNING_CODE_RESET_TIMEOUT_WASH             (1)     // 清洗机构复位超时
#define WARNING_CODE_RESET_TIMEOUT_REAGENTDISK      (2)     // 试剂盘机构复位超时
#define WARNING_CODE_RESET_TIMEOUT_REAGENT          (3)     // 试剂针机构复位超时
#define WARNING_CODE_RESET_TIMEOUT_SAMPLE           (4)     // 样本机构复位超时
#define WARNING_CODE_RESET_TIMEOUT_HANDCUP          (5)     // 抓杯机械手复位超时
#define WARNING_CODE_RESET_TIMEOUT_CUPSTACK         (6)     // 反应杯栈复位超时
#define WARNING_CODE_RESET_NG_REACT                 (7)     // 反应盘机构复位失败
#define WARNING_CODE_RESET_NG_WASH                  (8)     // 清洗机构复位失败
#define WARNING_CODE_RESET_NG_REAGENTDISK           (9)     // 试剂盘机构复位失败
#define WARNING_CODE_RESET_NG_REAGENT               (10)    // 试剂针机构复位失败
#define WARNING_CODE_RESET_NG_SAMPLE                (11)    // 样本机构复位失败
#define WARNING_CODE_RESET_NG_HANDCUP               (12)    // 抓杯机械手复位失败
#define WARNING_CODE_RESET_NG_CUPSTACK              (13)    // 反应杯栈复位失败

// Command
#define WARNING_CODE_CMD_RSP_GETITEM                (0)     // 获取测试数据超时

// React
#define WARNING_CODE_REACT_IF_HANDCUP               (1)     // 反应盘启动失败,被抓杯机械手干涉
#define WARNING_CODE_REACT_IF_REAGENT               (2)     // 反应盘启动失败,被试剂针干涉
#define WARNING_CODE_REACT_IF_SAMPLE                (3)     // 反应盘启动失败,被样本针干涉
#define WARNING_CODE_REACT_IF_MIX1                  (4)     // 反应盘启动失败,被试剂混匀1干涉
#define WARNING_CODE_REACT_IF_MIX2                  (5)     // 反应盘启动失败,被试剂混匀2干涉
#define WARNING_CODE_REACT_RUN_TRIGGER_23           (6)     // 反应盘23步转动触发丢失
#define WARNING_CODE_REACT_RUN_TRIGGER_2            (7)     // 反应盘2步转动触发丢失
#define WARNING_CODE_REACT_RUN_TRIGGER_9            (8)     // 反应盘9步转动触发丢失
#define WARNING_CODE_REACT_RUN_TRIGGER_31           (9)     // 反应盘31步转动触发丢失
#define WARNING_CODE_REACT_STOP_TRIGGER_23          (10)    // 反应盘23步停止触发丢失
#define WARNING_CODE_REACT_STOP_TRIGGER_2           (11)    // 反应盘2步停止触发丢失
#define WARNING_CODE_REACT_STOP_TRIGGER_9           (12)    // 反应盘9步停止触发丢失
#define WARNING_CODE_REACT_STOP_TRIGGER_31          (13)    // 反应盘31步停止触发丢失
#define WARNING_CODE_REACT_RUN_TYPE                 (14)    // 反应盘转动触发类型
#define WARNING_CODE_REACT_STOP_TYPE                (15)    // 反应盘停止触发类型
#define WARNING_CODE_REACT_IF_REAGENT2              (16)    // 反应盘启动失败,被试剂针2步干涉

// 
#define WARNING_CODE_WASHDISK_IF_NEEDLE             (1)     // 清洗针干涉清洗盘
#define WARNING_CODE_WASHDISK_IF_HANDCUP            (2)     // 抓杯机械手干涉清洗盘

// HandCup
#define WARNING_CODE_HANDCUP_INREACT_1              (1)     // 样本杯放入反应盘错误,反应盘已有反应杯
#define WARNING_CODE_HANDCUP_INREACT_2              (2)     // 样本杯放入反应盘错误,行程超时

// Reagent
#define WARNING_CODE_REAGENT_1_INJECT               (1)     // 试剂1注射失败
#define WARNING_CODE_REAGENT_2_INJECT               (2)     // 试剂2注射失败
#define WARNING_CODE_REAGENT_POSTION                (3)     // 试剂位置错误

// Cup Stack
#define WARNING_CODE_CUPSTACK_STATUS                (1)     // 新杯栈未就绪
#define WARNING_CODE_CUPSTACK_EMPTY                 (2)     // 杯盘已经无反应杯

// Flow
#define WARNING_CODE_FLOW_EMRACK_IN                 (1)     // 急诊样本架冲突
#define WARNING_CODE_FLOW_RACK_IN                   (2)     // 常规样本架冲突
#define WARNING_CODE_FLOW_ITEM_LOST                 (3)     // 丢失测试项,缓冲区没有足够空间
#define WARNING_CODE_FLOW_WASH_INCUP_STATE          (4)     // 清洗盘放反应杯时仍在运动
#define WARNING_CODE_FLOW_ITEM_LOST_RD              (5)     // 丢失测试项,测试中测试项丢失

// TimeOut
#define WARNING_CODE_TIMEOUT_REACT_STEP1            (1)     // 反应盘转动超时1
#define WARNING_CODE_TIMEOUT_REACT_STEP2            (2)     // 反应盘转动超时2
#define WARNING_CODE_TIMEOUT_REACT_STEP3            (3)     // 反应盘转动超时3
#define WARNING_CODE_TIMEOUT_REACT_STEP4            (4)     // 反应盘转动超时4
#define WARNING_CODE_TIMEOUT_REACT_MIX              (5)     // 反应盘混匀超时
#define WARNING_CODE_TIMEOUT_HANDCUP_CATCH_NEWCUP   (6)     // 机械手抓新杯超时
#define WARNING_CODE_TIMEOUT_HANDCUP_TO_REACT       (7)     // 机械手移动到反应盘超时
#define WARNING_CODE_TIMEOUT_HANDCUP_PUT_REACT      (8)     // 机械手放反应杯到反应盘超时
#define WARNING_CODE_TIMEOUT_HANDCUP_REACT_TO_WASH  (9)     // 机械手从反应盘到清洗盘超时
#define WARNING_CODE_TIMEOUT_HANDCUP_PUT_WASH       (10)    // 机械手放反应杯到清洗盘超时
#define WARNING_CODE_TIMEOUT_HANDCUP_TO_MR          (11)    // 机械手移动到测量室超时
#define WARNING_CODE_TIMEOUT_HANDCUP_PUT_MR         (12)    // 机械手放反应杯到测量室超时
#define WARNING_CODE_TIMEOUT_HANDCUP_MR_ABANDON     (13)    // 从测量室丢反应杯超时
#define WARNING_CODE_TIMEOUT_HANDCUP_WASH_TO_REACT  (14)    // 机械手从清洗盘到反应盘超时
#define WARNING_CODE_TIMEOUT_HANDCUP_WASH_PUT_REACT (15)    // 机械手放清洗盘反应杯到反应盘超时
#define WARNING_CODE_TIMEOUT_SAMPLE_TO_REACT        (16)    // 样本针移动到反应盘超时
#define WARNING_CODE_TIMEOUT_SAMPLE_ABSORB          (17)    // 样本针吸液超时
#define WARNING_CODE_TIMEOUT_SAMPLE_INJECT          (18)    // 样本针注液超时
#define WARNING_CODE_TIMEOUT_SAMPLE_FORCE_CLEAN     (19)    // 样本针强洗超时
#define WARNING_CODE_TIMEOUT_SAMPLE_CLEAN           (20)    // 样本针清洗超时
#define WARNING_CODE_TIMEOUT_RS1_R1_PREPARE         (21)    // 加试剂准备吸试剂1超时
#define WARNING_CODE_TIMEOUT_RS1_R1                 (22)    // 加试剂吸试剂1超时
#define WARNING_CODE_TIMEOUT_RS1_R2                 (23)    // 加试剂吸试剂2超时
#define WARNING_CODE_TIMEOUT_RS1_STEP2_R2_PREPARE   (24)    // 加试剂2步法准备吸试剂2超时
#define WARNING_CODE_TIMEOUT_RS1_STEP2_R2           (25)    // 加试剂2步法吸试剂2超时
#define WARNING_CODE_TIMEOUT_RS1_R1_INJECT          (26)    // 加试剂注射试剂超时
#define WARNING_CODE_TIMEOUT_RS2_R2_PREPARE         (27)    // 加磁珠准备吸试剂2超时
#define WARNING_CODE_TIMEOUT_RS2_R2                 (28)    // 加磁珠吸试剂2超时
#define WARNING_CODE_TIMEOUT_RS2_R3_CLEAN           (29)    // 加磁珠吸R3前清洗超时
#define WARNING_CODE_TIMEOUT_RS2_R3_PREPARE         (30)    // 加磁珠准备吸试剂3超时
#define WARNING_CODE_TIMEOUT_RS2_R3                 (31)    // 加磁珠吸试剂3超时
#define WARNING_CODE_TIMEOUT_RS2_M_CLEAN            (32)    // 加磁珠吸磁珠前清洗超时
#define WARNING_CODE_TIMEOUT_RS2_M_PREPARE          (33)    // 加磁珠准备吸磁珠超时
#define WARNING_CODE_TIMEOUT_RS2_M                  (34)    // 加磁珠吸磁珠超时
#define WARNING_CODE_TIMEOUT_RS2_INJECT             (35)    // 加磁珠排磁珠超时
#define WARNING_CODE_TIMEOUT_REAGENTDISK_MOVE       (36)    // 试剂盘转动超时
#define WARNING_CODE_TIMEOUT_WASH_ROTATE            (37)    // 清洗盘转动超时
#define WARNING_CODE_TIMEOUT_WASH_CLEAN             (38)    // 清洗针清洗超时
#define WARNING_CODE_TIMEOUT_MR_FULLOPEN            (39)    // 测量室开门超时
#define WARNING_CODE_TIMEOUT_MR_HALFOPEN            (40)    // 测量室半开门超时
#define WARNING_CODE_TIMEOUT_MR_CLOSE               (41)    // 测量室关门超时
#define WARNING_CODE_TIMEOUT_CB_MOVE_POSITION       (42)    // 将样本架移动到吸样位置超时
#define WARNING_CODE_TIMEOUT_CB_RECYCLE             (43)    // 将样本架移动到待抓取位置超时
#define WARNING_CODE_TIMEOUT_CUPSTACK_PUSH          (44)    // 推杯栈至测试位置超时
#define WARNING_CODE_TIMEOUT_CUPSTACK_CHANGE        (45)    // 置换新杯栈超时
#define WARNING_CODE_TIMEOUT_REAGENT_TO_REACT       (46)    // 试剂针移动到反应盘上方超时
// Api NG
#define WARNING_CODE_API_NG_REAGENT_ROTATE          (1)     // 试剂针旋转失败
#define WARNING_CODE_API_NG_ABSORB_RS1_R1_ING       (2)     // 加试剂吸R1时，试剂针吸R1失败
#define WARNING_CODE_API_NG_ABSORB_RS1_STEP2_R2     (3)     // 2步法吸试剂R2时，吸试剂失败
#define WARNING_CODE_API_NG_CLEAN_OUT               (4)     // 吸试剂后，试剂针清洗外壁失败
#define WARNING_CODE_API_NG_ABSORB_RS1_R2_ING       (5)     // 加试剂吸R2时，试剂针吸R2失败
#define WARNING_CODE_API_NG_INJECT_RS1              (6)     // 排试剂失败
#define WARNING_CODE_API_NG_CLEAN_INOUT             (7)     // 排试剂后，清洗试剂针内外壁失败
#define WARNING_CODE_API_NG_ABSORB_RS2_R2_ING       (8)     // 加磁珠时吸试剂2时，试剂针吸R2失败
#define WARNING_CODE_API_NG_ABSORB_RS2_R3_ING       (9)     // 加磁珠时吸试剂2时，试剂针吸R3失败
#define WARNING_CODE_API_NG_ABSORB_RS2_M_ING        (10)    // 加磁珠时吸试剂2时，试剂针吸磁珠失败
#define WARNING_CODE_API_NG_INJECT_RS2              (11)    // 排磁珠失败
#define WARNING_CODE_API_NG_REAGENTDISK_MOVE        (12)    // 试剂盘旋转失败
#define WARNING_CODE_API_NG_CONVEYORBELT_MOVE       (13)    // 样本传送带运送样本失败
#define WARNING_CODE_API_NG_SAMPLE_ROTATE           (14)    // 样本针旋转失败
#define WARNING_CODE_API_NG_ABSORB_SAMPLE           (15)    // 样本针吸液失败
#define WARNING_CODE_API_NG_INJECT_SAMPLE           (16)    // 样本针排液失败
#define WARNING_CODE_API_NG_SAMPLE_FORCE_CLEAN      (17)    // 样本针强洗失败
#define WARNING_CODE_API_NG_SAMPLE_CLEAN            (18)    // 样本针清洗失败
#define WARNING_CODE_API_NG_TO_CUPSTACK             (19)    // 抓杯机械手移动至新杯栈失败
#define WARNING_CODE_API_NG_TO_REACT                (20)    // 抓杯机械手移动至反应盘失败
#define WARNING_CODE_API_NG_TO_WASHDISK             (21)    // 抓杯机械手移动至清洗盘失败
#define WARNING_CODE_API_NG_TO_MR                   (22)    // 抓杯机械手移动至测量室失败
#define WARNING_CODE_API_NG_TO_GARBAGE              (23)    // 抓杯机械手移动至垃圾桶失败
#define WARNING_CODE_API_NG_HANDCUP_CATCH           (24)    // 抓杯机械手抓取反应杯失败
#define WARNING_CODE_API_NG_HANDCUP_PUT             (25)    // 抓杯机械手放反应杯失败
#define WARNING_CODE_API_NG_CUPSTACK_UPLOAD         (26)    // 新杯栈承载机构上传一个新盘到新盘装载平台失败
#define WARNING_CODE_API_NG_CUPSTACK_PUSH           (27)    // 新杯栈推手将一个新盘从新盘装载平台推送到测试平台失败
#define WARNING_CODE_API_NG_CUPSTACK_RECYCLE        (28)    // 新杯栈回收一个空盘失败
#define WARNING_CODE_API_NG_REACT_ROTATE            (29)    // 反应盘转动失败
#define WARNING_CODE_API_NG_REACT_MIX               (30)    // 反应盘混匀失败
#define WARNING_CODE_API_NG_WASHDISK_ROTATE         (31)    // 清洗盘转动失败
#define WARNING_CODE_API_NG_WASHNEEDLE_CLEAN1       (32)    // 清洗针第一次清洗失败
#define WARNING_CODE_API_NG_WASHNEEDLE_CLEAN2       (33)    // 清洗针第二次清洗失败
#define WARNING_CODE_API_NG_MR_FULLOPEN             (34)    // 测量室上门全开失败
#define WARNING_CODE_API_NG_MR_HALFOPEN             (35)    // 测量室上门半开失败
#define WARNING_CODE_API_NG_MR_CLOSE                (36)    // 测量室上门关闭失败
#define WARNING_CODE_API_NG_MR_BACK                 (37)    // 测量室本底测量失败
#define WARNING_CODE_API_NG_MR_VALUE                (38)    // 测量室测光测量失败

// Debug
#define WARNING_CODE_MSG_TO_TESTPROC                (1)     // 向测试任务发消息失败
#define WARNING_CODE_TESTPROC_MSG                   (2)     // 测试任务消息解析出错

const TESTPROC_WARNING_T g_stWarningCode[TESTPROC_WARNING_MAX] = 
{
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_COMM,      WARNING_CODE_COMMUNICATE},
    // Reset timeout
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_TIMEOUT_REACT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_TIMEOUT_WASH},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_TIMEOUT_REAGENTDISK},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_TIMEOUT_REAGENT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_TIMEOUT_SAMPLE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_TIMEOUT_HANDCUP},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_TIMEOUT_CUPSTACK},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_NG_REACT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_NG_WASH},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_NG_REAGENTDISK},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_NG_REAGENT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_NG_SAMPLE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_NG_HANDCUP},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_RESET,     WARNING_CODE_RESET_NG_CUPSTACK},
    // Command
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_CMD,       WARNING_CODE_CMD_RSP_GETITEM},
    // React
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_IF_HANDCUP},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_IF_REAGENT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_IF_SAMPLE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_IF_MIX1},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_IF_MIX2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_RUN_TRIGGER_23},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_RUN_TRIGGER_2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_RUN_TRIGGER_9},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_RUN_TRIGGER_31},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_STOP_TRIGGER_23},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_STOP_TRIGGER_2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_STOP_TRIGGER_9},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_STOP_TRIGGER_31},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_RUN_TYPE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_STOP_TYPE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_REACT,     WARNING_CODE_REACT_IF_REAGENT2},
    // Wash    
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_WASH,      WARNING_CODE_WASHDISK_IF_NEEDLE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_EMSTOP,     WARNING_TYPE_WASH,      WARNING_CODE_WASHDISK_IF_HANDCUP},
    // HandCup
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_HANDCUP,   WARNING_CODE_HANDCUP_INREACT_1},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_HANDCUP,   WARNING_CODE_HANDCUP_INREACT_2},
    // Reagent
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_REAGENT,   WARNING_CODE_REAGENT_1_INJECT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_REAGENT,   WARNING_CODE_REAGENT_2_INJECT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_REAGENT,   WARNING_CODE_REAGENT_POSTION},
    // Cup Stack
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_CUPSTACK,  WARNING_CODE_CUPSTACK_STATUS},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_CUPSTACK,  WARNING_CODE_CUPSTACK_EMPTY},
    // Flow
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_FLOW,      WARNING_CODE_FLOW_EMRACK_IN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_FLOW,      WARNING_CODE_FLOW_RACK_IN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_FLOW,      WARNING_CODE_FLOW_ITEM_LOST},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_FLOW,      WARNING_CODE_FLOW_WASH_INCUP_STATE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_FLOW,      WARNING_CODE_FLOW_ITEM_LOST_RD},
    // Timeout
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_REACT_STEP1},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_REACT_STEP2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_REACT_STEP3},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_REACT_STEP4},    
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_REACT_MIX},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_CATCH_NEWCUP},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_TO_REACT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_PUT_REACT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_REACT_TO_WASH},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_PUT_WASH},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_TO_MR},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_PUT_MR},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_MR_ABANDON},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_WASH_TO_REACT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_HANDCUP_WASH_PUT_REACT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_SAMPLE_TO_REACT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_SAMPLE_ABSORB},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_SAMPLE_INJECT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_SAMPLE_FORCE_CLEAN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_SAMPLE_CLEAN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS1_R1_PREPARE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS1_R1},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS1_R2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS1_STEP2_R2_PREPARE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS1_STEP2_R2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS1_R1_INJECT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_R2_PREPARE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_R2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_R3_CLEAN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_R3_PREPARE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_R3},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_M_CLEAN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_M_PREPARE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_M},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_RS2_INJECT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_REAGENTDISK_MOVE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_WASH_ROTATE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_WASH_CLEAN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_MR_FULLOPEN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_MR_HALFOPEN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_MR_CLOSE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_CB_MOVE_POSITION},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_CB_RECYCLE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_CUPSTACK_PUSH},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_CUPSTACK_CHANGE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_TIMEOUT,   WARNING_CODE_TIMEOUT_REAGENT_TO_REACT},
    // Api NG
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_REAGENT_ROTATE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_ABSORB_RS1_R1_ING},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_ABSORB_RS1_STEP2_R2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_CLEAN_OUT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_ABSORB_RS1_R2_ING},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_INJECT_RS1},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_CLEAN_INOUT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_ABSORB_RS2_R2_ING},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_ABSORB_RS2_R3_ING},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_ABSORB_RS2_M_ING},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_INJECT_RS2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_REAGENTDISK_MOVE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_CONVEYORBELT_MOVE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_SAMPLE_ROTATE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_ABSORB_SAMPLE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_STOP,       WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_INJECT_SAMPLE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_SAMPLE_FORCE_CLEAN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_SAMPLE_CLEAN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_TO_CUPSTACK},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_TO_REACT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_TO_WASHDISK},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_TO_MR},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_TO_GARBAGE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_HANDCUP_CATCH},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_HANDCUP_PUT},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_CUPSTACK_UPLOAD},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_CUPSTACK_PUSH},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_CUPSTACK_RECYCLE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_REACT_ROTATE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_REACT_MIX},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_WASHDISK_ROTATE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_WASHNEEDLE_CLEAN1},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_WASHNEEDLE_CLEAN2},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_MR_FULLOPEN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_MR_HALFOPEN},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_MR_CLOSE},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_MR_BACK},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_NOTICE,     WARNING_TYPE_API_NG,    WARNING_CODE_API_NG_MR_VALUE},
    // Debug
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_DEBUG,      WARNING_TYPE_DEBUG_1,   WARNING_CODE_MSG_TO_TESTPROC},
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_DEBUG,      WARNING_TYPE_DEBUG_1,   WARNING_CODE_TESTPROC_MSG},
    // None
    {BOARD_ID_CELL_MAIN,     WARNING_LEVEL_DEBUG,      0,   0}
};


